### ISSUE TITLE
exit code 1

### ISSUE THREAD

**Issue by victormartins** [makaroni4/sandi_meter#40]
I was doing a rake task to run sandi_meter automatically, however, it is failing:
```
rake aborted!
Command failed with status (1): [sandi_meter -dg...]
/Users/vgm/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/file_utils.rb:55:in `block in create_shell_runner'
/Users/vgm/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `call'
/Users/vgm/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `sh'
```

I think everything ran ok, cause I get the report, but the problem is that the exit code is one:
```
>>sandi_meter -dg
>>echo $?
1
```

My rake task is:
```
namespace :qa do
  desc 'runs sandi meter and generates a report'
  task :sandi_meter do
    sh 'sandi_meter -dg'
  end
end
```

Am I missing something, or there is a problem with the exit code?

**Comment by makaroni4** [comment]
@victormartins haha it's been a long time but it's all done! So happy! :beers:

**Comment by victormartins** [comment]
Congratulations :beers:  :)
